[package]
name = "voxelhex"
version = "0.1.0"
edition = "2021"
authors = ["Dávid Tóth <toth.david.munka@gmail.com>"]
license = "MIT OR Apache-2.0"

[features]
default = ["bevy_wgpu","bytecode", "dot_vox_support"]
bytecode = ["dep:bendy"]
serialization = ["dep:serde"]
dot_vox_support = ["dep:dot_vox", "dep:nalgebra", "dep:bendy"]
bevy_wgpu = ["dep:bevy", "dep:crossbeam", "dep:bimap", "dep:bevy_panorbit_camera", "dep:iyes_perf_ui"]

[dependencies]
num-traits = "0.2.19"
serde = { version = "1.0.217", features = ["derive"], optional = true }
bendy = { git = "https://github.com/P3KI/bendy.git" , features = ["std", "serde"], optional = true }
dot_vox = { version = "5.1.1", optional = true }
nalgebra = { version = "0.33.0", optional = true }
crossbeam = { version = "0.8.4", optional = true }
bimap = { version = "0.6.3", optional = true }
bevy = { version = "0.15.3", features = ["dynamic_linking"], optional = true}
bevy_dylib = { version = "0.15.0-rc.3" }
iyes_perf_ui = { version = "0.4.0", features = [], optional = true}
bevy_panorbit_camera = { version = "0.21.1", features = [], optional = true}
bytemuck = "1.23.0"

# debugging
#linker = "/usr/bin/clang"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
#[profile.release] # for flamegraph
#debug = true

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable some optimizations in debug mode
[profile.dev]
opt-level = 3

[dev-dependencies]
#lldb = "0.0.11" to enable debugging support
# maybe try lldb-sys?!
rand = "0.8.5"
criterion = { version = "0.4", features = ["html_reports"] }
